apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-continuous-delivery
  namespace: knative-serving
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      serviceAccountName: controller
      containers:
      - image: ko://github.com/googleinterns/knative-continuous-delivery/cmd/controller
        env:
        - name: SYSTEM_NAMESPACE
          # value: "default"
          # value: "istio-system"
          # value: "knative-serving"
          # value: "kube-node-lease"
          # value: "kube-public"
          value: "kube-system"
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability